# .github/workflows/android.yml
name: Android CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Make gradlew executable
      run: |
        # 如果gradlew不存在，下载它
        if [ ! -f gradlew ]; then
          wget -q https://raw.githubusercontent.com/gradle/gradle/master/gradlew
          chmod +x gradlew
        else
          chmod +x gradlew
        fi
    
    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: pure-tcm-battle-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    
    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: pure-tcm-battle-release
        path: app/build/outputs/apk/release/app-release.apk
    
    - name: Upload to GitHub Releases
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/app-release.apk
        tag_name: v1.0.0
        name: 纯中医对战 v1.0.0
        body: |
          首个版本发布！
          功能：
          - 六经辨证对战
          - 经方治疗系统
          - 病情传变模拟
