name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Create required Gradle files
      run: |
        # 创建 gradle-wrapper.properties 文件
        mkdir -p gradle/wrapper
        cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF
        
        # 创建 settings.gradle.kts
        cat > settings.gradle.kts << 'EOF'
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "MedicalBattleGame"
include(":app")
EOF
        
        # 创建 build.gradle.kts (root)
        cat > build.gradle.kts << 'EOF'
plugins {
    id("com.android.application") version "8.1.2" apply false
    id("org.jetbrains.kotlin.android") version "1.9.0" apply false
}
EOF
        
        # 创建 app/build.gradle.kts
        mkdir -p app
        cat > app/build.gradle.kts << 'EOF'
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.medical.battle"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.medical.battle"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
}
EOF
        
        # 创建 local.properties
        echo "sdk.dir=$ANDROID_HOME" > local.properties
    
    - name: Grant execute permission for gradlew
      run: |
        # 如果 gradlew 不存在，创建它
        if [ ! -f gradlew ]; then
          wget https://raw.githubusercontent.com/gradle/gradle/master/gradlew
          chmod +x gradlew
        else
          chmod +x gradlew
        fi
    
    - name: Build with Gradle
      run: |
        # 先运行 wrapper 任务生成 wrapper 文件
        ./gradlew wrapper --gradle-version 8.2
        
        # 清理并构建
        ./gradlew clean
        ./gradlew build
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
